### ISSUE TITLE
Join process via consensus

### ISSUE THREAD

**Issue by andrecronje** [andrecronje/lachesis#8]
Nodes are currently a fixed peer list, allow new nodes to join via consensus agreement of all participants using the same poset graph

**Comment by Maxime2** [comment]
A few questions:
- should we also consider removing a node from peer list and how it could be implemented? i.e. node self-removal should be obviously straightforward, should we consider node removal on consensus of other nodes?
- How can we use the same poset graph for peer list changes? Currently nodes do not look inside transactions. Would it better to maintain a separate poset graph for peer list so nodes will look into  transactions in this poset for operations over peer list?

**Comment by SamuelMarks** [comment]
To start with, we should confirm that all nodes joining have the same version. Otherwise they are rejected. Later, we can use a more detailed version scheme, like the SSH standard has: https://tools.ietf.org/html/rfc4253#section-4.2

[![seq0](https://user-images.githubusercontent.com/807580/47403375-0f348800-d795-11e8-8882-734c60060c02.png)](https://mermaidjs.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoic2VxdWVuY2VEaWFncmFtXG4gICAgcGFydGljaXBhbnQgQm9iXG4gICAgcGFydGljaXBhbnQgUmFuZG9tIHBhcnRpY2lwYW50XG4gICAgcGFydGljaXBhbnQgTmV0d29ya1xuICAgIEJvYi0-Pk5ldHdvcms6IFJFUSB0byBqb2luIG5ldHdvcmtcbiAgICBOZXR3b3JrLT4-UmFuZG9tIHBhcnRpY2lwYW50OiBcbiAgICBSYW5kb20gcGFydGljaXBhbnQtPj5Cb2I6IEFDSyBSRVEsIHNlbmQgZGF0YVxuICAgIEJvYi0tPk5ldHdvcms6IE1lbWJlciBvZiBuZXR3b3JrIiwibWVybWFpZCI6eyJ0aGVtZSI6ImZvcmVzdCJ9fQ)

I'm thinking in the REQ stage you could include the version in a header—see aforementioned RFC—you could send:

    lachesis-0.3.3-5916fe75<CR><LF>

Then, in the ACK REQ stage you could confirm that the version strings equals its own version string, and if it does, accept it into the peers list & thus the network.

(obviously this has no security advantage, as anyone can fake versions, but it is handy for non security related stability and debugging)
